### ISSUE TITLE
No files were processed in the specified paths.

### ISSUE THREAD

**Issue by Minori-ty** [tobua/bun-biome-rsbuild#1]
in windows10

When I use "npm run format:biome", then an error and  "No files were processed in the specified paths" is displayed

**Comment by tobua** [comment]
I tried it on macOS with Node.js and it works fine. Bun itself, that's used for this project, will soon have full support for Windows but not yet.

The Biome docs use relative paths, maybe that will fix your issue: `biome format ./**.{ts,tsx} --write`

I don't have Windows available currently, so I cannot test this, here are some other options you can try:

`biome format index.tsx --write` (if this works there is no glob support on Windows)
`biome format ./**/*.{ts,tsx} --write` (nested folders missing)
`biome format . --write` (best option matches all files for me)

I've noticed that the glob in general also doesn't work well on macOS, however the last option matching everything works fine so I added that. File extensions also seem to have issues. Biome is still experimental.

The template is [now using](https://github.com/tobua/bun-biome-rsbuild/commit/e78bd04b64f3f440f58063dcf24bc2d8fe90bf09) `biome format . --write` which matches all files except the ones ignored in `biome.json`.

Let me know which option works on Windows?

**Comment by Minori-ty** [comment]
> I tried it on macOS with Node.js and it works fine. Bun itself, that's used for this project, will soon have full support for Windows but not yet.
> 
> The Biome docs use relative paths, maybe that will fix your issue: `biome format ./**.{ts,tsx} --write`
> 
> I don't have Windows available currently, so I cannot test this, here are some other options you can try:
> 
> `biome format index.tsx --write` (if this works there is no glob support on Windows) `biome format ./**/*.{ts,tsx} --write` (nested folders missing) `biome format . --write` (best option matches all files for me)
> 
> I've noticed that the glob in general also doesn't work well on macOS, however the last option matching everything works fine so I added that. File extensions also seem to have issues. Biome is still experimental.
> 
> The template is [now using](https://github.com/tobua/bun-biome-rsbuild/commit/e78bd04b64f3f440f58063dcf24bc2d8fe90bf09) `biome format . --write` which matches all files except the ones ignored in `biome.json`.
> 
> Let me know which option works on Windows?

Thank you for your answer. `biome format index.tsx --write` and `biome format . --write` is useful.
However, when I want to specify a suffix, such as formatting *.tsx, biome doesn't seem to support the "./" syntax
